@startuml
skinparam dpi 200
skinparam classAttributeFontSize 8
skinparam classArrowFontSize 9
skinparam classFontSize 10
skinparam nodesep 90
skinparam ranksep 40
hide stereotype
skinparam class {
	BackgroundColor White
	BackgroundColor<<Test>> LightPink
	BackgroundColor<<User>> LightBlue
	BackgroundColor<<Group>> LightGreen
}

abstract class User <<User>> {
    String username, password, email
}

class Teacher <<User>> extends User {
}

class Student <<User>> extends User {
    Integer level, group
}

class Test <<Test>> {
    Integer nbOfQuestions, level
    Float mark
    String subject
}

class Theory <<Group>> {
    String text, url
}

class Group <<Group>> {
    Integer level
}

class SubGroup <<Group>> {
    Integer level
    String subject
}

class Question <<Group>> {
    Integer level, id
    String question, answer, subject
}

Test "*" -left- "1..*" Student: do <
SubGroup "*" -left- "*" Student: studies <
Group "0..1" -left- "*" Student: joins <

Group "*" -left- "1" Teacher: creates <
SubGroup "*" -left- "1" Teacher: creates <
Question "*" -left- "1" Teacher: creates <
Theory "*" -left- "1" Teacher: creates <

Question "*" -up- "*" SubGroup: composes >
Theory "*" -up- "*" SubGroup: composes >
Group "1" -up- "*" SubGroup: composes <

Question "*" -- "*" Test: composes >
Group "*" -- "1" Test: has >
@enduml