@startuml
skinparam dpi 200
skinparam classAttributeFontSize 8
skinparam classArrowFontSize 9
skinparam classFontSize 10
skinparam nodesep 90
skinparam ranksep 40
hide stereotype
skinparam class {
	BackgroundColor White
	BackgroundColor<<Test>> LightPink
	BackgroundColor<<User>> LightBlue
	BackgroundColor<<Group>> LightGreen
}

abstract class User <<User>> {
    String username, password, email
}

class Teacher <<User>> extends User {
}

class Student <<User>> extends User {
    Integer level, group
}

abstract class Test <<Test>> {
    Integer nbOfQuestions
    Float mark
}

class EvaluationTest <<Test>> extends Test {
}

class GroupTest <<Test>> extends Test {
    Integer level
    String subject
}

class Group <<Group>> {
    Integer level
}

class SubGroup <<Group>> {
    Integer level
    String subject
}

class Question <<Group>> {
    Integer level, id
    String question, answer, subject
}

EvaluationTest "1" -left- "*" Student: do <
GroupTest "*" -- "1..*" Student: do <
SubGroup "*" -- "*" Student: studies <
Group "0..1" -- "*" Student: joins <

Group "*" -- "1" Teacher: creates <
SubGroup "*" -- "1" Teacher: creates <
Question "*" -- "1" Teacher: creates <

Question "*" -up- "*" SubGroup: composes >
Group "1" -up- "*" SubGroup: composes <

Question "*" -- "*" Test: composes >
Group "*" -- "1" GroupTest: has >
@enduml