@startuml
skinparam dpi 200
skinparam classAttributeFontSize 8
skinparam classArrowFontSize 9
skinparam classFontSize 10
skinparam nodesep 90
skinparam ranksep 40
hide stereotype
skinparam class {
	BackgroundColor White
	BackgroundColor<<Exam>> LightPink
	BackgroundColor<<User>> LightBlue
	BackgroundColor<<Level>> LightGreen
}

abstract class User <<User>> {
    String username, password, email, role
}

class Teacher <<User>> extends User {
}

class Student <<User>> extends User {
    Integer level
}



abstract class Exam <<Exam>> {
    Integer nbOfQuestions
}

class EvaluationExam <<Exam>> extends Exam {
    Float point
}

class FinalLevelExam <<Exam>> extends Exam {
     Integer level
     Float mark
     String subject
}

class Theory <<Level>> {
    String text, url
}

class Level <<Level>> {
    Integer level
}

class Topic <<Level>> {
    Integer level
    String subject
}

class Question <<Level>> {
    Integer level, id
    String question, answer, subject
}

EvaluationExam "1" -left- "*" Student: do <
FinalLevelExam "1" -left- "*" Level: has <
Topic "*" -left- "*" Student: studies <
Level "0..1" -left- "*" Student: joins <

Level "*" -left- "1" Teacher: creates <
Topic "*" -left- "1" Teacher: creates <
Question "*" -left- "1" Teacher: creates <
Theory "*" -left- "1" Teacher: creates <

Question "*" -up- "*" Topic: composes >
Theory "*" -up- "*" Topic: composes >
Level "1" -up- "*" Topic: composes <

Question "*" -- "*" Exam: composes >
@enduml